'use client'

import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0b0a]">
      <header className="border-b border-white/[0.06] bg-[#0a0b0a]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2">
            <img src="/icon.png" alt="" className="h-7 w-7" />
            <span className="text-lg font-bold text-white">Magical AI</span>
          </Link>
          <nav className="flex items-center gap-6">
            <Link href="/" className="text-sm text-white/50 hover:text-white transition">Home</Link>
            <Link href="/community" className="text-sm text-white/50 hover:text-white transition">Community</Link>
            <Link href="/auth/login" className="text-sm text-white/60 hover:text-white transition">Sign In</Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-16">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-white/40 mb-8">Last updated: August 23, 2026</p>

        <div className="space-y-8 text-sm text-white/65 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Magical AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to modify these terms at any time.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>Magical AI is an AI-powered application builder that generates web applications from natural language prompts. The Service uses third-party AI models and sandbox environments to generate, preview, and deploy code.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. User Responsibilities</h2>
            <p>You are solely responsible for:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 ml-4">
              <li>All content you generate, store, or deploy using the Service</li>
              <li>Ensuring generated code does not violate any applicable laws or third-party rights</li>
              <li>Securing your account credentials and API keys</li>
              <li>Any costs incurred through your use of third-party services (AI providers, sandbox providers)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Intellectual Property</h2>
            <p>All code, content, and applications generated by Magical AI are yours. You retain full ownership of anything you create. Magical AI claims no ownership over your generated projects.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Third-Party Services</h2>
            <p>The Service integrates with third-party providers (AI models, sandbox environments, hosting). Your use of these services is subject to their respective terms. Magical AI is not liable for any third-party service failures, data loss, or security breaches.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Disclaimer of Warranties</h2>
            <p className="font-medium text-white/80">THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
            <p className="mt-2">We do not guarantee: (a) the Service will be uninterrupted or error-free; (b) generated code will be bug-free or production-ready; (c) the Service will meet your specific requirements.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p className="font-medium text-white/80">IN NO EVENT SHALL MAGICAL AI, ITS DEVELOPERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA, REVENUE, OR PROFITS, ARISING FROM YOUR USE OF THE SERVICE.</p>
            <p className="mt-2">Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Indemnification</h2>
            <p>You agree to indemnify and hold harmless Magical AI and its developers from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
            <p>We may terminate or suspend your access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service ceases immediately.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the modified terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="https://github.com/officialpriyam/magical/issues" className="text-blue-400 hover:underline" target="_blank" rel="noopener noreferrer">GitHub Issues</a>.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
