export interface NJTTemplate {
  id: string
  name: string
  slug: string
  description: string
  category: string
  previewImage: string
  githubRepo: string
  demoUrl?: string
  tags: string[]
}

export const njtCategories = [
  'All',
  'SaaS',
  'Starter',
  'E-Commerce',
  'Admin',
  'Blog',
  'Portfolio',
  'AI',
  'Landing Page',
  'Vue',
] as const

export const njtTemplates: NJTTemplate[] = [
  {
    id: 'play',
    name: 'Play',
    slug: 'play',
    description: 'Free, open-source SaaS starter kit and boilerplate perfect for SaaS startups, apps, and businesses.',
    category: 'SaaS',
    previewImage: 'https://api.nextjstemplates.com/image/Play---Free-SaaS-Boilerplate-and-Starter-Kit-for-Next.js-84ee9b1d-e287-4964-9cca-5495d9c8422d-play-next.png',
    githubRepo: 'https://github.com/NextJSTemplates/play-nextjs',
    demoUrl: 'https://play.nextjstemplates.com',
    tags: ['SaaS', 'Starter', 'Free'],
  },
  {
    id: 'solid',
    name: 'Solid',
    slug: 'solid',
    description: 'Robust Next.js SaaS boilerplate and starter kit, crafted for creating fully-functional SaaS startup websites.',
    category: 'SaaS',
    previewImage: 'https://api.nextjstemplates.com/image/Solid---Next.js-SaaS-Boilerplate-240bb6f5-9812-461a-871d-0d4f723d0923.png',
    githubRepo: 'https://github.com/NextJSTemplates/solid-nextjs',
    tags: ['SaaS', 'Starter', 'Boilerplate'],
  },
  {
    id: 'ai-tool',
    name: 'AI Tool',
    slug: 'ai-tool',
    description: 'OpenAI + Next.js SaaS Boilerplate and Starter kit for building SaaS applications using OpenAI and AI.',
    category: 'AI',
    previewImage: 'https://api.nextjstemplates.com/image/ai-tool-1.3.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/openai-nextjs-starter',
    tags: ['AI', 'SaaS', 'OpenAI'],
  },
  {
    id: 'ai-starter-kit',
    name: 'AI Starter Kit',
    slug: 'ai-starter-kit',
    description: 'Next.js AI Website Templates with a SaaS Starter Kit featuring prebuilt AI tools, auth, billing, dashboards.',
    category: 'AI',
    previewImage: 'https://api.nextjstemplates.com/image/ai-starter.jpg',
    githubRepo: 'https://github.com/AIStarterKit/ai-saas-starter-kit-nextjs',
    tags: ['AI', 'SaaS', 'Starter'],
  },
  {
    id: 'nextcommerce',
    name: 'NextCommerce',
    slug: 'nextcommerce',
    description: 'All-in-one eCommerce boilerplate template built on Next.js + Sanity for managing your online store.',
    category: 'E-Commerce',
    previewImage: 'https://api.nextjstemplates.com/image/nextcommerce-njt.jpg',
    githubRepo: 'https://github.com/NextMerce/nextjs-ecommerce-template',
    tags: ['E-Commerce', 'Sanity', 'Store'],
  },
  {
    id: 'shopify-nextjs',
    name: 'Shopify + Next.js',
    slug: 'shopify-nextjs-template',
    description: 'Comprehensive eCommerce store solution built for Next.js and Tailwind CSS with Shopify integration.',
    category: 'E-Commerce',
    previewImage: 'https://api.nextjstemplates.com/image/Shopify-+-Next.js-Starter-Template-7df4d0ba-87df-44c4-a30c-e5bf1b58668e.jpg',
    githubRepo: 'https://github.com/btahir/next-shopify-starter',
    tags: ['E-Commerce', 'Shopify', 'Store'],
  },
  {
    id: 'tailadmin',
    name: 'TailAdmin',
    slug: 'tailadmin-nextjs-admin-dashboard',
    description: 'Free and open-source Next.js admin dashboard template built with Tailwind CSS and TypeScript.',
    category: 'Admin',
    previewImage: 'https://api.nextjstemplates.com/image/tailadmin-njt.jpg',
    githubRepo: 'https://github.com/TailAdmin/free-nextjs-admin-dashboard',
    tags: ['Admin', 'Dashboard', 'Free'],
  },
  {
    id: 'nextadmin',
    name: 'NextAdmin',
    slug: 'nextadmin',
    description: 'Next.js admin dashboard toolkit with over 200 UI components and templates for admin panels.',
    category: 'Admin',
    previewImage: 'https://api.nextjstemplates.com/image/nextadmin.jpg',
    githubRepo: 'https://github.com/NextAdminHQ/nextjs-admin-dashboard',
    tags: ['Admin', 'Dashboard', 'Components'],
  },
  {
    id: 'nextblog',
    name: 'NextBlog',
    slug: 'nextblog',
    description: 'Creative Next.js blog template designed for high-end blog sites, blogging solutions, and publishing platforms.',
    category: 'Blog',
    previewImage: 'https://api.nextjstemplates.com/image/NextBlog---Next.js-Blog-Template-and--Publishing-Platform-Starter-Kit-1e90b107-1024-4869-9a53-f8a3d953eeb8-nextblog-new.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/nextblog',
    tags: ['Blog', 'Publishing'],
  },
  {
    id: 'notion-blog',
    name: 'Notion Blog',
    slug: 'nextjs-notion-blog',
    description: 'Next.js blog template with Notion integration — harness the power of Notion as your CMS.',
    category: 'Blog',
    previewImage: 'https://api.nextjstemplates.com/image/Next.js-Blog-Template-with-Notion-Integration-a71d2c02-8e49-4485-a673-af20ac861c28.jpg',
    githubRepo: 'https://github.com/ijjk/notion-blog',
    tags: ['Blog', 'Notion', 'CMS'],
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    slug: 'nextjs-portfolio',
    description: 'Free Next.js portfolio template with sleek, modern design for professionals.',
    category: 'Portfolio',
    previewImage: 'https://api.nextjstemplates.com/image/Free-Next.js-Portfolio-Template-db56a0a9-420c-4507-8a89-2a431d37fbf8.jpg',
    githubRepo: 'https://github.com/chetanverma16/react-portfolio-template',
    tags: ['Portfolio', 'Free', 'Personal'],
  },
  {
    id: 'nextui-landing',
    name: 'NextUI Landing',
    slug: 'nextui-nextjs',
    description: 'Free and open-source Next.js Landing page template for SaaS companies using NextUI.',
    category: 'Landing Page',
    previewImage: 'https://api.nextjstemplates.com/image/NextUI-+-Next.js-Landing-Page-Template-d108537a-b787-4b7b-99e1-e61effb4401b.jpg',
    githubRepo: 'https://github.com/Siumauricio/landing-template-nextui',
    tags: ['Landing Page', 'NextUI', 'Free'],
  },
  {
    id: 'unft',
    name: 'uNFT Marketplace',
    slug: 'unft',
    description: 'Free and open-source Next.js template for creating decentralized NFT marketplaces.',
    category: 'E-Commerce',
    previewImage: 'https://api.nextjstemplates.com/image/uNFT---Next.js-NFT-Marketplace-Template-c2de9fea-ac7c-4b50-bd03-e397e8bde877.png',
    githubRepo: 'https://github.com/cosmicjs/unft-marketplace',
    tags: ['NFT', 'Web3', 'Marketplace'],
  },
  {
    id: 'finorio',
    name: 'Finorio',
    slug: 'finorio',
    description: 'Modern Next.js boilerplate for building personal finance, fintech applications and digital wallet websites.',
    category: 'SaaS',
    previewImage: 'https://api.nextjstemplates.com/image/finorio.png',
    githubRepo: 'https://github.com/NextJSTemplates/finorio-nextjs',
    tags: ['Finance', 'Fintech', 'SaaS'],
  },
  {
    id: 'agency',
    name: 'Agency',
    slug: 'agency',
    description: 'All-in-one Next.js starter kit designed specifically for agencies and portfolio websites.',
    category: 'Portfolio',
    previewImage: 'https://api.nextjstemplates.com/image/agency-nextjs.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/agency-nextjs',
    tags: ['Agency', 'Portfolio', 'Starter'],
  },
  {
    id: 'crypto',
    name: 'Crypto',
    slug: 'crypto',
    description: 'Powerful Next.js template for fully functional cryptocurrency, ICO, and blockchain project websites.',
    category: 'Landing Page',
    previewImage: 'https://api.nextjstemplates.com/image/crypto-nextjs.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/crypto-nextjs',
    tags: ['Crypto', 'Blockchain', 'Web3'],
  },
  {
    id: 'appline',
    name: 'Appline',
    slug: 'appline',
    description: 'Ultimate Next.js App website template for building mobile app landing pages and software showcases.',
    category: 'Landing Page',
    previewImage: 'https://api.nextjstemplates.com/image/appline-nextjs.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/appline-nextjs',
    tags: ['App', 'Landing Page', 'Software'],
  },
  {
    id: 'base',
    name: 'Base',
    slug: 'base',
    description: 'Definitive boilerplate and starter kit for Next.js designed specifically for SaaS businesses.',
    category: 'SaaS',
    previewImage: 'https://api.nextjstemplates.com/image/base-nextjs.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/base-nextjs',
    tags: ['SaaS', 'Boilerplate', 'Starter'],
  },
  {
    id: 'go',
    name: 'Go',
    slug: 'go',
    description: 'SaaS Business boilerplate and starter kit template specifically crafted for SaaS businesses and startups.',
    category: 'SaaS',
    previewImage: 'https://api.nextjstemplates.com/image/Go---Next.js-SaaS-Boilerplate-and-Landing-Page-for-Business-3b36650f-19e6-40ef-8dd1-45c08cbacd76-go-nextjs.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/go-nextjs',
    tags: ['SaaS', 'Startup', 'Landing Page'],
  },
  {
    id: 'saas-starter',
    name: 'SaaS Starter',
    slug: 'saas-starter-startup',
    description: 'Next.js SaaS boilerplate and starter crafted for full-functional SaaS startup websites with Auth, DB, Blog.',
    category: 'Starter',
    previewImage: 'https://api.nextjstemplates.com/image/Next.js-SaaS-Starter-Kit-and-Boilerplate-for-Startups-282e26f7-f543-4ae4-a777-ac306c08cce8-startup-pro.jpg',
    githubRepo: 'https://github.com/NextJSTemplates/saas-starter-nextjs',
    tags: ['SaaS', 'Starter', 'Auth'],
  },

  // ── Creative Tim Vue.js Templates ──────────────────────────────────
  {
    id: 'ct-vuetify-material-dashboard',
    name: 'Vuetify Material Dashboard',
    slug: 'vuetify-material-dashboard',
    description: 'Free Vue.js admin template built with Vuetify, Material Design, and Vue CLI. Features a clean dashboard with charts and tables.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/100/thumb/opt_md_vuetify_thumbnail.jpg?1539698855',
    githubRepo: 'https://github.com/creativetimofficial/vuetify-material-dashboard',
    tags: ['Vue', 'Admin', 'Vuetify', 'Material'],
  },
  {
    id: 'ct-vue-material-dashboard',
    name: 'Vue Material Dashboard',
    slug: 'vue-material-dashboard',
    description: 'Free Vue.js admin template with Material Design. Clean UI with sidebar navigation, charts, and data tables.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/81/thumb/opt_md_vue_thumbnail.jpg?1534938464',
    githubRepo: 'https://github.com/creativetimofficial/vue-material-dashboard',
    tags: ['Vue', 'Admin', 'Material'],
  },
  {
    id: 'ct-vue-light-bootstrap',
    name: 'Vue Light Bootstrap Dashboard',
    slug: 'vue-light-bootstrap-dashboard',
    description: 'Free Bootstrap 4 Vue.js admin dashboard with a light theme, perfect for data-heavy applications.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/67/thumb/opt_lbd_vue_thumbnail.jpg?1534959550',
    githubRepo: 'https://github.com/creativetimofficial/vue-light-bootstrap-dashboard',
    tags: ['Vue', 'Admin', 'Bootstrap'],
  },
  {
    id: 'ct-vue-argon-design',
    name: 'Vue Argon Design System',
    slug: 'vue-argon-design-system',
    description: 'Free design system for Bootstrap 4 and Vue.js with reusable components and pre-built sections.',
    category: 'Starter',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/92/thumb/opt_argon_vue_thumbnail.jpg?1534236902',
    githubRepo: 'https://github.com/creativetimofficial/vue-argon-design-system',
    tags: ['Vue', 'Design System', 'Bootstrap'],
  },
  {
    id: 'ct-vue-paper-dashboard',
    name: 'Vue Paper Dashboard',
    slug: 'vue-paper-dashboard',
    description: 'Free Bootstrap Vue.js admin template with a clean paper-style design and dashboard widgets.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/57/thumb/opt_pd_vue_thumbnail.jpg?1534959668',
    githubRepo: 'https://github.com/creativetimofficial/vue-paper-dashboard',
    tags: ['Vue', 'Admin', 'Bootstrap'],
  },
  {
    id: 'ct-vue-black-dashboard',
    name: 'Vue Black Dashboard',
    slug: 'vue-black-dashboard',
    description: 'Free dark-themed Bootstrap 4 Vue.js admin template with modern UI and rich components.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/99/thumb/opt_bd_vue_thumbnail.jpg?1539595932',
    githubRepo: 'https://github.com/creativetimofficial/vue-black-dashboard',
    tags: ['Vue', 'Admin', 'Dark'],
  },
  {
    id: 'ct-vue-material-kit-2',
    name: 'Vue Material Kit 2',
    slug: 'vue-material-kit-2',
    description: 'Free VueJS 3 & Bootstrap 5 UI kit with Material Design components for building modern landing pages.',
    category: 'Landing Page',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/97/thumb/vue-material-kit-2.jpg?1660910610',
    githubRepo: 'https://github.com/creativetimofficial/vue-material-kit',
    tags: ['Vue', 'UI Kit', 'Material', 'Landing'],
  },
  {
    id: 'ct-vue-argon-dashboard-2',
    name: 'Vue Argon Dashboard 2',
    slug: 'vue-argon-dashboard-2',
    description: 'Free Bootstrap 5 Vue.js 3 admin template with Argon Design System and modern dashboard components.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/156/thumb/vue-argon-dashboard.jpg?1653536619',
    githubRepo: 'https://github.com/creativetimofficial/vue-argon-dashboard',
    tags: ['Vue', 'Admin', 'Bootstrap 5', 'Vue 3'],
  },
  {
    id: 'ct-vue-now-ui-kit',
    name: 'Vue Now UI Kit',
    slug: 'vue-now-ui-kit',
    description: 'Free Bootstrap Vue.js UI kit with Now Design System for building stunning web applications.',
    category: 'Starter',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/94/thumb/opt_nuk_vue_thumbnail_%281%29.jpg?1535015651',
    githubRepo: 'https://github.com/creativetimofficial/vue-now-ui-kit',
    tags: ['Vue', 'UI Kit', 'Bootstrap'],
  },
  {
    id: 'ct-vue-notus',
    name: 'Vue Notus',
    slug: 'vue-notus',
    description: 'Free Tailwind CSS UI Kit and Admin built with Vue.js for modern web applications.',
    category: 'Starter',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/333/thumb/opt_ad_bootstrapvue_thumbnail.jpg?1595854718',
    githubRepo: 'https://github.com/creativetimofficial/vue-notus',
    tags: ['Vue', 'Tailwind', 'UI Kit'],
  },
  {
    id: 'ct-muse-vue-ant-design',
    name: 'Muse Vue Ant Design',
    slug: 'muse-vue-ant-design-dashboard',
    description: 'Free Ant Design Vue dashboard template with elegant UI components and data visualization.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/333/thumb/opt_ad_bootstrapvue_thumbnail.jpg?1595854718',
    githubRepo: 'https://github.com/creativetimofficial/muse-vue-ant-design-dashboard',
    tags: ['Vue', 'Admin', 'Ant Design'],
  },
  {
    id: 'ct-nuxt-black-dashboard',
    name: 'Nuxt Black Dashboard',
    slug: 'nuxt-black-dashboard',
    description: 'Free Bootstrap 4 Nuxt.js admin template with dark theme and rich dashboard components.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/99/thumb/opt_bd_vue_thumbnail.jpg?1539595932',
    githubRepo: 'https://github.com/creativetimofficial/nuxt-black-dashboard',
    tags: ['Nuxt', 'Admin', 'Dark'],
  },
  {
    id: 'ct-bootstrapvue-argon',
    name: 'BootstrapVue Argon Dashboard',
    slug: 'bootstrapvue-argon-dashboard',
    description: 'Free BootstrapVue admin template with Argon Design System for Vue.js applications.',
    category: 'Admin',
    previewImage: 'https://s3.amazonaws.com/creativetim_bucket/products/333/thumb/opt_ad_bootstrapvue_thumbnail.jpg?1595854718',
    githubRepo: 'https://github.com/creativetimofficial/argon-dashboard-bootstrapvue',
    tags: ['Vue', 'Admin', 'BootstrapVue'],
  },
]
