import type { GeneratedFile } from '@/lib/fragment-files'

export type StarterTemplateInfo = {
  repository: string
  cliInit: string
  description: string
}

export const STARTER_TEMPLATE_INFO: Record<string, StarterTemplateInfo> = {
  'nextjs-developer': {
    repository: 'https://github.com/vercel/next.js/tree/canary/packages/create-next-app/templates/app-tw-empty/ts',
    cliInit: 'npx create-next-app@latest my-app --typescript --tailwind --app',
    description: 'Next.js App Router + TypeScript + Tailwind CSS starter',
  },
  'react-developer': {
    repository: 'https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react-ts',
    cliInit: 'npm create vite@latest my-app -- --template react-ts',
    description: 'Vite React + TypeScript starter',
  },
  'vite-developer': {
    repository: 'https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react-ts',
    cliInit: 'npm create vite@latest my-app -- --template react-ts',
    description: 'Vite React + TypeScript starter',
  },
  'vue-developer': {
    repository: 'https://github.com/vuejs/create-vue',
    cliInit: 'npm create vue@latest',
    description: 'Vue 3 + TypeScript starter generated by create-vue',
  },
  'svelte-developer': {
    repository: 'https://github.com/sveltejs/kit/tree/main/packages/create-svelte',
    cliInit: 'npm create svelte@latest my-app',
    description: 'SvelteKit + TypeScript starter generated by create-svelte',
  },
}

export function getStarterTemplateInfo(template?: string) {
  return template ? STARTER_TEMPLATE_INFO[template] : undefined
}

export function getStarterTemplateFiles(template?: string): GeneratedFile[] | null {
  if (template === 'nextjs-developer') return getNextAppRouterStarter()
  if (template === 'react-developer' || template === 'vite-developer') return getViteReactStarter()
  if (template === 'vue-developer') return getVueStarter()
  if (template === 'svelte-developer') return getSvelteKitStarter()
  return null
}

function commonFiles(name: string, description: string): GeneratedFile[] {
  return [
    {
      path: 'README.md',
      content: `# ${name}\n\n${description}\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Notes\n\nThis workspace starts from the framework starter scaffold. Magical AI edits, creates, deletes, and renames files on top of that starter to build the requested project.\n`,
    },
    {
      path: '.gitignore',
      content: [
        '# dependencies',
        'node_modules/',
        '.pnp',
        '.pnp.js',
        '',
        '# build output',
        'dist/',
        'build/',
        '.next/',
        '.svelte-kit/',
        '.vercel/',
        '',
        '# environment',
        '.env',
        '.env.local',
        '.env.development.local',
        '.env.test.local',
        '.env.production.local',
        '',
        '# misc',
        '.DS_Store',
        '*.tsbuildinfo',
      ].join('\n'),
    },
  ]
}

function tailwindCss() {
  return '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;\n}\n\nbody {\n  margin: 0;\n  min-width: 320px;\n  min-height: 100vh;\n}\n'
}

function getNextAppRouterStarter(): GeneratedFile[] {
  return [
    ...commonFiles('Next.js App', 'A Next.js App Router TypeScript application with Tailwind CSS.'),
    {
      path: 'package.json',
      content: JSON.stringify({
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: 'latest',
          react: 'latest',
          'react-dom': 'latest',
        },
        devDependencies: {
          '@types/node': 'latest',
          '@types/react': 'latest',
          '@types/react-dom': 'latest',
          autoprefixer: 'latest',
          postcss: 'latest',
          tailwindcss: 'latest',
          typescript: 'latest',
        },
      }, null, 2),
    },
    {
      path: 'app/layout.tsx',
      content: 'import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "Magical App",\n  description: "Generated with Magical AI",\n};\n\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n',
    },
    {
      path: 'app/page.tsx',
      content: 'export default function Home() {\n  return <main className="min-h-screen">Start building with Magical AI.</main>;\n}\n',
    },
    {
      path: 'app/globals.css',
      content: tailwindCss(),
    },
    {
      path: 'tailwind.config.ts',
      content: 'import type { Config } from "tailwindcss";\n\nconst config: Config = {\n  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],\n  theme: { extend: {} },\n  plugins: [],\n};\n\nexport default config;\n',
    },
    {
      path: 'postcss.config.mjs',
      content: 'const config = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n\nexport default config;\n',
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          paths: { '@/*': ['./*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      }, null, 2),
    },
  ]
}

function getViteReactStarter(): GeneratedFile[] {
  return [
    ...commonFiles('Vite React App', 'A Vite React TypeScript application with Tailwind CSS.'),
    {
      path: 'package.json',
      content: JSON.stringify({
        type: 'module',
        scripts: {
          dev: 'vite --host 0.0.0.0',
          build: 'tsc -b && vite build',
          preview: 'vite preview --host 0.0.0.0',
        },
        dependencies: {
          '@vitejs/plugin-react': 'latest',
          vite: 'latest',
          typescript: 'latest',
          react: 'latest',
          'react-dom': 'latest',
        },
        devDependencies: {
          '@types/react': 'latest',
          '@types/react-dom': 'latest',
          autoprefixer: 'latest',
          postcss: 'latest',
          tailwindcss: 'latest',
        },
      }, null, 2),
    },
    {
      path: 'index.html',
      content: '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>Vite React App</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n',
    },
    {
      path: 'src/main.tsx',
      content: 'import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport "./index.css";\nimport App from "./App";\n\ncreateRoot(document.getElementById("root")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n',
    },
    {
      path: 'src/App.tsx',
      content: 'export default function App() {\n  return <main className="min-h-screen">Start building with Magical AI.</main>;\n}\n',
    },
    {
      path: 'src/index.css',
      content: tailwindCss(),
    },
    {
      path: 'vite.config.ts',
      content: 'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { host: "0.0.0.0" },\n});\n',
    },
    {
      path: 'tailwind.config.ts',
      content: 'import type { Config } from "tailwindcss";\n\nconst config: Config = {\n  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],\n  theme: { extend: {} },\n  plugins: [],\n};\n\nexport default config;\n',
    },
    {
      path: 'postcss.config.js',
      content: 'export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n',
    },
  ]
}

function getVueStarter(): GeneratedFile[] {
  return [
    ...commonFiles('Vue App', 'A Vue 3 TypeScript application using the create-vue/Vite starter shape.'),
    {
      path: 'package.json',
      content: JSON.stringify({
        type: 'module',
        scripts: {
          dev: 'vite --host 0.0.0.0',
          build: 'vue-tsc -b && vite build',
          preview: 'vite preview --host 0.0.0.0',
        },
        dependencies: {
          vue: 'latest',
        },
        devDependencies: {
          '@vitejs/plugin-vue': 'latest',
          vue: 'latest',
          'vue-tsc': 'latest',
          vite: 'latest',
          typescript: 'latest',
          autoprefixer: 'latest',
          postcss: 'latest',
          tailwindcss: 'latest',
        },
      }, null, 2),
    },
    {
      path: 'index.html',
      content: '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>Vue App</title>\n  </head>\n  <body>\n    <div id="app"></div>\n    <script type="module" src="/src/main.ts"></script>\n  </body>\n</html>\n',
    },
    {
      path: 'src/main.ts',
      content: 'import { createApp } from "vue";\nimport "./assets/main.css";\nimport App from "./App.vue";\n\ncreateApp(App).mount("#app");\n',
    },
    {
      path: 'src/App.vue',
      content: '<template>\n  <main class="min-h-screen">Start building with Magical AI.</main>\n</template>\n',
    },
    {
      path: 'src/assets/main.css',
      content: tailwindCss(),
    },
    {
      path: 'vite.config.ts',
      content: 'import { defineConfig } from "vite";\nimport vue from "@vitejs/plugin-vue";\n\nexport default defineConfig({\n  plugins: [vue()],\n  server: { host: "0.0.0.0" },\n});\n',
    },
    {
      path: 'tailwind.config.ts',
      content: 'import type { Config } from "tailwindcss";\n\nconst config: Config = {\n  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],\n  theme: { extend: {} },\n  plugins: [],\n};\n\nexport default config;\n',
    },
    {
      path: 'postcss.config.js',
      content: 'export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n',
    },
  ]
}

function getSvelteKitStarter(): GeneratedFile[] {
  return [
    ...commonFiles('SvelteKit App', 'A SvelteKit TypeScript application with Tailwind CSS.'),
    {
      path: 'package.json',
      content: JSON.stringify({
        type: 'module',
        scripts: {
          dev: 'vite dev --host 0.0.0.0',
          build: 'vite build',
          preview: 'vite preview --host 0.0.0.0',
          check: 'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json',
        },
        dependencies: {
          '@sveltejs/adapter-auto': 'latest',
          '@sveltejs/kit': 'latest',
          svelte: 'latest',
        },
        devDependencies: {
          '@sveltejs/vite-plugin-svelte': 'latest',
          svelte: 'latest',
          'svelte-check': 'latest',
          vite: 'latest',
          typescript: 'latest',
          autoprefixer: 'latest',
          postcss: 'latest',
          tailwindcss: 'latest',
        },
      }, null, 2),
    },
    {
      path: 'src/app.html',
      content: '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    %sveltekit.head%\n  </head>\n  <body data-sveltekit-preload-data="hover">\n    <div style="display: contents">%sveltekit.body%</div>\n  </body>\n</html>\n',
    },
    {
      path: 'src/routes/+page.svelte',
      content: '<main class="min-h-screen">Start building with Magical AI.</main>\n',
    },
    {
      path: 'src/app.css',
      content: tailwindCss(),
    },
    {
      path: 'src/routes/+layout.svelte',
      content: '<script lang="ts">\n  import "../app.css";\n  let { children } = $props();\n</script>\n\n{@render children()}\n',
    },
    {
      path: 'svelte.config.js',
      content: 'import adapter from "@sveltejs/adapter-auto";\nimport { vitePreprocess } from "@sveltejs/vite-plugin-svelte";\n\nconst config = {\n  preprocess: vitePreprocess(),\n  kit: { adapter: adapter() },\n};\n\nexport default config;\n',
    },
    {
      path: 'vite.config.ts',
      content: 'import { sveltekit } from "@sveltejs/kit/vite";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({\n  plugins: [sveltekit()],\n  server: { host: "0.0.0.0" },\n});\n',
    },
    {
      path: 'tailwind.config.ts',
      content: 'import type { Config } from "tailwindcss";\n\nconst config: Config = {\n  content: ["./src/**/*.{html,js,svelte,ts}"],\n  theme: { extend: {} },\n  plugins: [],\n};\n\nexport default config;\n',
    },
    {
      path: 'postcss.config.js',
      content: 'export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n',
    },
  ]
}
